### PR TITLE
Fixed typo for strings.xml for all other translation files.

### PR DESCRIPTION
**Pull request by vijaykakadiya**
I pushed this change into new branch(develop) I created in my local repo. So creating this another pull request. Sorry about that.

### CODE REVIEW

**Comment by barbeau** [comment]
@vijaykakadiya Thanks for submitting this!  However, this build is failing on Travis - see:
https://travis-ci.org/CUTR-at-USF/OpenTripPlanner-for-Android/builds/53276637

Looks like the edit to the code didn't make it into this PR.

I think your best bet is to start a new branch off master (e.g., issue354), and then put all these edits (and the ones in #461) there in a single commit.  Then, open a new PR from that new branch.  Please be sure to run the tests in Android Studio as well to make sure that everything builds and passes before submitting the PR.  Also, we use the format for the commit title to be "Fix #54 - Fix typo in strings.xml", so the issue is referenced directly in the commit.  If the issue is referenced in the commit like this, then Github will automatically close the issue when the commit is merged.

I'm going to close this and the other PR for now so you can start fresh.

**Comment by barbeau** [comment]
Note that an easy way to combine these commits is to squash them (and the other commit in the other PR) - see http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits.

**Comment by barbeau** [comment]
I also noticed that OTP Android build tools version needed to be updated before it would compile in the current version of Android Studio, so I just updated the master branch of the main repo with that info.  So, you can just sync your master with the upstream repo (see https://help.github.com/articles/syncing-a-fork/) and then everything should be ready to go in Android Studio, and you'll only need to make your string changes.

**Comment by vijaykakadiya** [comment]
Ok. I'll do that. :+1:

**Pull request closed without merging**
